#!/bin/sh
set -e

echo "Running continous integration..."

echo "[1/3] Running code formatter..."
sh ./ci/run_formatter.sh

echo "[2/3] Running linter..."
sh ./ci/run_linter.sh

echo "[3/3] Running unit tests..."
sh ./ci/run_tests.sh